export const SET_QUERY_SEARCH = 'SET_QUERY_SEARCH';
export const SET_DATE_FILTER = 'SET_DATE_FILTER';
export const SET_TYPE_FILTER = 'SET_TYPE_FILTER';
export const SET_ORDER_FILTER = 'SET_ORDER_FILTER';
export const GET_SEARCH_RESULTS = 'GET_SEARCH_RESULTS';
export const GET_VIDEOS = 'GET_VIDEOS';
export const GET_CHANNELS = 'GET_CHANNELS';
export const TOGGLE_SCROLL_LOADING = 'TOGGLE_SCROLL_LOADING';
